"""Build an AI public-source review ledger for flagged Bangladesh PSDQ rows.

This script reads the automated facility-validation coded screen and writes a
row-level review ledger for the sampled DGHS rows that still require review.
It uses only already-committed public-source artifacts: the DGHS sample rows,
the cached OSM/Overpass candidate screen, and the geoBoundaries coordinate
status generated by the coded-screen script.

Constitution guardrails: public data only (§2.1), auditable numbers (§2.2),
AI-first honest labeling (§18.2), and no composite headline claims (§6.4).
"""

from __future__ import annotations

import csv
import json
import math
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "generated"

CODED_SCREEN_CSV = OUT_DIR / "psdq-bgd-facility-validation-coded-screen.csv"
OSM_CANDIDATES_CSV = OUT_DIR / "psdq-bgd-facility-validation-osm-candidates.csv"
CODED_SUMMARY_JSON = OUT_DIR / "psdq-bgd-facility-validation-coded-summary.json"

OUT_REVIEW_CSV = OUT_DIR / "psdq-bgd-facility-validation-ai-review.csv"
OUT_REVIEW_SUMMARY_JSON = OUT_DIR / "psdq-bgd-facility-validation-ai-review-summary.json"

REVIEW_METHOD = "ai_public_source_row_review_v1"
STATUS = "ai_public_source_row_review_not_human_validation"
NON_CLAIM = (
    "This is an AI-first public-source row-review ledger over the automated "
    "coded screen. It is not a human validation pass, not ground truth, not a "
    "facility-quality assessment, and not a service-access estimate."
)

VALIDATION_CODE_LABELS = {
    "confirmed_same_facility": "confirmed same facility",
    "probable_duplicate_or_alias": "probable duplicate or alias",
    "classification_mismatch": "classification mismatch",
    "registry_coordinate_issue": "registry coordinate issue",
    "missing_public_map_point": "missing public-map point",
    "osm_only_candidate": "OSM-only candidate",
    "unresolved_public_sources": "unresolved public sources",
}

BUCKET_ORDER = [
    "public_map_gap_at_valid_coordinate",
    "registry_coordinate_repair",
    "candidate_name_or_type_resolution",
    "nearby_osm_without_registry_match",
    "unresolved_public_source_check",
]

PRIORITY_ORDER = [
    "priority_1_candidate_resolution",
    "priority_1_high_exposure_map_gap",
    "priority_2_coordinate_source_check",
    "priority_3_public_map_gap_spot_check",
    "priority_4_unresolved_source_check",
]


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def int_value(value: Any) -> int:
    try:
        return int(float(str(value or "").strip()))
    except (TypeError, ValueError):
        return 0


def float_value(value: Any) -> float | None:
    try:
        number = float(str(value or "").strip())
    except (TypeError, ValueError):
        return None
    if not math.isfinite(number):
        return None
    return number


def format_candidate(candidate: dict[str, str]) -> str:
    name = candidate.get("osm_name", "").strip() or "(unnamed)"
    return (
        f"{candidate.get('osm_id', '')}|{name}|"
        f"{candidate.get('osm_amenity', '')}|"
        f"{candidate.get('candidate_distance_m', '')}m|"
        f"name={candidate.get('name_score', '')}|"
        f"score={candidate.get('candidate_score', '')}"
    )


def candidate_groups(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[row.get("dghs_id", "")].append(row)
    for rows_for_id in grouped.values():
        rows_for_id.sort(
            key=lambda item: (
                -(float_value(item.get("candidate_score")) or 0.0),
                float_value(item.get("candidate_distance_m")) or 999_999.0,
            )
        )
    return dict(grouped)


def top_candidate_evidence(candidates: list[dict[str, str]], limit: int = 3) -> str:
    if not candidates:
        return ""
    return "; ".join(format_candidate(candidate) for candidate in candidates[:limit])


def review_classification(row: dict[str, str]) -> dict[str, str]:
    code = row.get("validation_code", "")
    group = row.get("sample_group", "")
    coord_status = row.get("coordinate_boundary_status", "")
    candidate_name = row.get("candidate_osm_name", "").strip() or "an unnamed OSM health feature"
    distance = row.get("candidate_distance_m", "")
    name_score = row.get("best_name_score", "")
    dghs_category = row.get("best_dghs_category", "")
    osm_category = row.get("best_osm_category", "")

    if code == "registry_coordinate_issue":
        if coord_status == "missing_or_invalid_coordinate":
            note = "The DGHS sample row does not carry a usable coordinate, so map matching cannot start from this row."
            question = "Can a public DGHS page, registry export, or official gazette provide a valid facility coordinate?"
        else:
            note = "The DGHS coordinate falls outside the expected sampled upazila boundary in geoBoundaries ADM3."
            question = "Is the DGHS coordinate stale, miscoded, or attached to a different administrative unit?"
        return {
            "ai_review_bucket": "registry_coordinate_repair",
            "ai_review_disposition": "coordinate_source_issue_before_map_matching",
            "evidence_strength": "high_for_coordinate_issue_only",
            "review_priority": "priority_2_coordinate_source_check",
            "ai_review_notes": note,
            "human_followup_question": question,
        }

    if code == "missing_public_map_point":
        high_gap = group in {"high_exposure_gap", "zero_osm_high_proxy"}
        priority = "priority_1_high_exposure_map_gap" if high_gap else "priority_3_public_map_gap_spot_check"
        return {
            "ai_review_bucket": "public_map_gap_at_valid_coordinate",
            "ai_review_disposition": "no_osm_health_feature_within_500m_of_valid_registry_coordinate",
            "evidence_strength": "high_for_pinned_osm_snapshot_absence",
            "review_priority": priority,
            "ai_review_notes": (
                "The DGHS coordinate is usable for this screen and the pinned all-Bangladesh OSM health cache "
                "contains no amenity=hospital/clinic/doctors feature within 500 meters."
            ),
            "human_followup_question": (
                "Does manual public-map inspection confirm that the facility is absent from OSM at this coordinate, "
                "or is it mapped under another tag/name outside the health-feature query?"
            ),
        }

    if code == "classification_mismatch":
        return {
            "ai_review_bucket": "candidate_name_or_type_resolution",
            "ai_review_disposition": "nearby_candidate_has_name_signal_but_facility_class_differs",
            "evidence_strength": "medium_public_source_signal",
            "review_priority": "priority_1_candidate_resolution",
            "ai_review_notes": (
                f"The best OSM candidate is {candidate_name} at {distance} meters. "
                f"The automated screen read DGHS as {dghs_category or 'unknown'} and OSM as {osm_category or 'unknown'} "
                f"with name score {name_score or 'missing'}."
            ),
            "human_followup_question": (
                "Should the row be treated as the same facility with a map classification difference, "
                "or as a nearby different facility?"
            ),
        }

    if code == "probable_duplicate_or_alias":
        return {
            "ai_review_bucket": "candidate_name_or_type_resolution",
            "ai_review_disposition": "nearby_candidate_may_be_alias_duplicate_or_same_campus",
            "evidence_strength": "medium_public_source_signal",
            "review_priority": "priority_1_candidate_resolution",
            "ai_review_notes": (
                f"The best OSM candidate is {candidate_name} at {distance} meters with name score "
                f"{name_score or 'missing'}, but the automated evidence is not strong enough for a same-facility code."
            ),
            "human_followup_question": (
                "Do public names, signs, or official facility pages indicate an alias, duplicate row, shared campus, "
                "or separate nearby facility?"
            ),
        }

    if code == "osm_only_candidate":
        return {
            "ai_review_bucket": "nearby_osm_without_registry_match",
            "ai_review_disposition": "nearby_osm_health_feature_does_not_match_sampled_registry_name",
            "evidence_strength": "medium_for_nearby_osm_presence_low_for_row_match",
            "review_priority": "priority_1_candidate_resolution",
            "ai_review_notes": (
                f"The best nearby OSM feature is {candidate_name} at {distance} meters, but the name signal does "
                "not support a match to the sampled DGHS row."
            ),
            "human_followup_question": (
                "Is the nearby OSM health feature an unmapped registry facility, a non-DGHS facility, "
                "or a separate public-map feature in the same neighborhood?"
            ),
        }

    return {
        "ai_review_bucket": "unresolved_public_source_check",
        "ai_review_disposition": "public_sources_do_not_support_a_stable_row_code",
        "evidence_strength": "low",
        "review_priority": "priority_4_unresolved_source_check",
        "ai_review_notes": (
            f"The automated screen assigned {VALIDATION_CODE_LABELS.get(code, code or 'unknown code')}, "
            "but this review pass cannot separate the row with the public artifacts available."
        ),
        "human_followup_question": "What additional public source is needed before this row can be coded?",
    }


def order_key(row: dict[str, Any]) -> tuple[int, int, str, int, int]:
    priority = str(row.get("review_priority", ""))
    bucket = str(row.get("ai_review_bucket", ""))
    return (
        PRIORITY_ORDER.index(priority) if priority in PRIORITY_ORDER else len(PRIORITY_ORDER),
        BUCKET_ORDER.index(bucket) if bucket in BUCKET_ORDER else len(BUCKET_ORDER),
        str(row.get("sample_group", "")),
        int_value(row.get("upazila_sample_order")),
        int_value(row.get("facility_sample_order")),
    )


def count_rows(rows: list[dict[str, Any]], key: str, order: list[str] | None = None) -> list[dict[str, Any]]:
    counter = Counter(str(row.get(key, "")) for row in rows)
    keys = order or sorted(counter)
    output = [{"name": item, "rows": int(counter.get(item, 0))} for item in keys if counter.get(item, 0)]
    for item in sorted(counter):
        if order and item not in order:
            output.append({"name": item, "rows": int(counter[item])})
    return output


def group_bucket_counts(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, Counter[str]] = defaultdict(Counter)
    for row in rows:
        grouped[str(row["sample_group"])][str(row["ai_review_bucket"])] += 1
    output = []
    for group in sorted(grouped):
        item: dict[str, Any] = {"sample_group": group, "rows": int(sum(grouped[group].values()))}
        for bucket in BUCKET_ORDER:
            item[bucket] = int(grouped[group].get(bucket, 0))
        output.append(item)
    return output


def main() -> None:
    for path in [CODED_SCREEN_CSV, OSM_CANDIDATES_CSV, CODED_SUMMARY_JSON]:
        if not path.exists():
            raise FileNotFoundError(path)

    coded_rows = read_csv(CODED_SCREEN_CSV)
    candidate_rows = read_csv(OSM_CANDIDATES_CSV)
    coded_summary = json.loads(CODED_SUMMARY_JSON.read_text(encoding="utf-8"))
    candidates_by_dghs = candidate_groups(candidate_rows)

    flagged = [row for row in coded_rows if int_value(row.get("manual_review_recommended")) == 1]
    review_rows: list[dict[str, Any]] = []
    review_date = now_utc()[:10]

    for row in flagged:
        dghs_id = row.get("dghs_id", "")
        candidates = candidates_by_dghs.get(dghs_id, [])
        classification = review_classification(row)
        review_rows.append(
            {
                "attestation_chain": "ai-first",
                "review_method": REVIEW_METHOD,
                "review_date": review_date,
                **{key: row.get(key, "") for key in [
                    "sample_group",
                    "upazila_sample_order",
                    "facility_sample_order",
                    "division_name",
                    "district_name",
                    "upazila_name",
                    "join_key",
                    "dghs_id",
                    "dghs_code",
                    "facility_name",
                    "facility_type_name",
                    "facility_level_name",
                    "facility_healthcare_level_name",
                    "is_private",
                    "is_principal_tier",
                    "is_clinical_tier",
                    "has_valid_coordinate",
                    "latitude",
                    "longitude",
                    "validation_code",
                    "validation_notes",
                    "coordinate_boundary_status",
                    "coordinate_inside_sampled_upazila",
                    "osm_candidate_count_500m",
                    "candidate_osm_id",
                    "candidate_osm_name",
                    "candidate_osm_amenity",
                    "candidate_distance_m",
                    "best_candidate_score",
                    "best_name_score",
                    "best_dghs_category",
                    "best_osm_category",
                    "overpass_status",
                    "overpass_cache_file",
                    "overpass_retrieved_at",
                ]},
                **classification,
                "top_candidate_evidence": top_candidate_evidence(candidates),
                "source_basis": (
                    "DGHS sampled registry row; automated OSM candidate screen within 500 meters; "
                    "geoBoundaries ADM3 coordinate status; pinned Overpass cache where applicable."
                ),
                "non_claim": NON_CLAIM,
            }
        )

    review_rows.sort(key=order_key)
    for index, row in enumerate(review_rows, start=1):
        row["review_id"] = f"PSDQ-BGD-AI-{index:03d}"

    fields = [
        "review_id",
        "attestation_chain",
        "review_method",
        "review_date",
        "sample_group",
        "upazila_sample_order",
        "facility_sample_order",
        "division_name",
        "district_name",
        "upazila_name",
        "join_key",
        "dghs_id",
        "dghs_code",
        "facility_name",
        "facility_type_name",
        "facility_level_name",
        "facility_healthcare_level_name",
        "is_private",
        "is_principal_tier",
        "is_clinical_tier",
        "has_valid_coordinate",
        "latitude",
        "longitude",
        "validation_code",
        "validation_notes",
        "coordinate_boundary_status",
        "coordinate_inside_sampled_upazila",
        "osm_candidate_count_500m",
        "candidate_osm_id",
        "candidate_osm_name",
        "candidate_osm_amenity",
        "candidate_distance_m",
        "best_candidate_score",
        "best_name_score",
        "best_dghs_category",
        "best_osm_category",
        "overpass_status",
        "overpass_cache_file",
        "overpass_retrieved_at",
        "ai_review_bucket",
        "ai_review_disposition",
        "evidence_strength",
        "review_priority",
        "ai_review_notes",
        "human_followup_question",
        "top_candidate_evidence",
        "source_basis",
        "non_claim",
    ]
    write_csv(OUT_REVIEW_CSV, review_rows, fields)

    candidate_resolution_rows = [
        row
        for row in review_rows
        if row["ai_review_bucket"] in {"candidate_name_or_type_resolution", "nearby_osm_without_registry_match"}
    ]
    summary = {
        "generated_at": now_utc(),
        "program": "public-service-data-quality",
        "country": "Bangladesh",
        "attestation_chain": "ai-first",
        "status": STATUS,
        "goal_level": "L3 AI public-source review ledger",
        "unit": "sampled DGHS clinical facility row flagged by automated public-source screen",
        "source_inputs": [
            {
                "path": str(CODED_SCREEN_CSV.relative_to(ROOT)),
                "role": "automated validation-code screen and coordinate status",
            },
            {
                "path": str(OSM_CANDIDATES_CSV.relative_to(ROOT)),
                "role": "ranked OSM health candidates within 500 meters of sampled DGHS coordinates",
            },
            {
                "path": str(CODED_SUMMARY_JSON.relative_to(ROOT)),
                "role": "screen summary, public-source metadata, and non-claim",
            },
        ],
        "public_validation_sources": coded_summary.get("public_validation_sources", []),
        "review_scope": {
            "coded_rows": len(coded_rows),
            "flagged_rows_reviewed": len(review_rows),
            "unflagged_rows_not_reopened": len(coded_rows) - len(review_rows),
            "candidate_resolution_rows": len(candidate_resolution_rows),
            "rows_with_no_osm_health_candidate_500m": sum(
                1 for row in review_rows if row["ai_review_bucket"] == "public_map_gap_at_valid_coordinate"
            ),
            "coordinate_source_issue_rows": sum(
                1 for row in review_rows if row["ai_review_bucket"] == "registry_coordinate_repair"
            ),
        },
        "ai_review_bucket_counts": count_rows(review_rows, "ai_review_bucket", BUCKET_ORDER),
        "ai_review_priority_counts": count_rows(review_rows, "review_priority", PRIORITY_ORDER),
        "validation_code_counts_in_review_queue": count_rows(
            review_rows,
            "validation_code",
            [
                "missing_public_map_point",
                "registry_coordinate_issue",
                "classification_mismatch",
                "probable_duplicate_or_alias",
                "osm_only_candidate",
                "unresolved_public_sources",
            ],
        ),
        "ai_review_bucket_counts_by_group": group_bucket_counts(review_rows),
        "non_claim": NON_CLAIM,
        "outputs": {
            "review_csv": str(OUT_REVIEW_CSV.relative_to(ROOT)),
            "summary_json": str(OUT_REVIEW_SUMMARY_JSON.relative_to(ROOT)),
        },
    }
    write_json(OUT_REVIEW_SUMMARY_JSON, summary)

    print(
        "Built BGD AI public-source review ledger: "
        f"{len(review_rows)} flagged rows, "
        f"{summary['review_scope']['candidate_resolution_rows']} candidate-resolution rows.",
        flush=True,
    )
    print(f"Wrote {OUT_REVIEW_CSV}", flush=True)
    print(f"Wrote {OUT_REVIEW_SUMMARY_JSON}", flush=True)


if __name__ == "__main__":
    main()
