"""Structured evidence base for the Task 31 welfare-loss review.

All estimates retain the unit and counterfactual used by the source.  They must
not be summed unless the review explicitly states that the populations,
periods, concepts, and baselines are comparable.
"""

EVIDENCE = [
    {
        "id": "C01", "category": "COVID-19", "study": "Asian Development Bank (2021a)",
        "year": 2021, "source": "ADB report", "geography": "Developing Asia",
        "subregion": "Regional", "population": "All residents", "shock": "COVID-19 pandemic",
        "welfare_indicator": "GDP relative to a no-pandemic baseline",
        "estimate": "6.0%-9.5% of regional GDP in 2020 and 3.6%-6.3% in 2021",
        "methodology": "Global macroeconomic scenario model with epidemiological and containment channels",
        "identification": "Modelled counterfactual, not causal micro-identification",
        "limitations": "Range depends on pandemic and policy scenarios; GDP is not a complete welfare metric",
        "confidence": "Medium", "evidence_type": "Modelled counterfactual",
        "url": "https://www.adb.org/publications/macroeconomic-impact-covid-19-developing-asia", "doi": ""
    },
    {
        "id": "C02", "category": "COVID-19", "study": "Asian Development Bank (2021b)",
        "year": 2021, "source": "Key Indicators for Asia and the Pacific 2021", "geography": "Developing Asia",
        "subregion": "Regional", "population": "People near international poverty lines", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Extreme and moderate poverty",
        "estimate": "75-80 million additional people in extreme poverty in 2020; roughly 170-180 million additional people below the broader poverty line",
        "methodology": "Growth-to-poverty simulation against a no-COVID baseline",
        "identification": "Model-based nowcast",
        "limitations": "Sensitive to poverty line, survey vintage, distributional pass-through, and baseline growth",
        "confidence": "Medium", "evidence_type": "Poverty simulation",
        "url": "https://www.adb.org/sites/default/files/publication/720461/ki2021.pdf", "doi": ""
    },
    {
        "id": "C03", "category": "COVID-19", "study": "International Labour Organization (2020)",
        "year": 2020, "source": "Asia-Pacific Employment and Social Outlook 2020", "geography": "Asia and the Pacific",
        "subregion": "Regional", "population": "Working-age population", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Employment and working poverty",
        "estimate": "81 million jobs lost in 2020; working-hour losses pushed an additional 22-25 million workers into working poverty",
        "methodology": "ILO nowcasting model combining labour-force, national accounts, and high-frequency data",
        "identification": "Modelled deviation from pre-crisis expectations",
        "limitations": "Informal work and hours are imputed where real-time data are incomplete",
        "confidence": "Medium", "evidence_type": "Nowcast",
        "url": "https://www.ilo.org/publications/asia-pacific-employment-and-social-outlook-2020-navigating-crisis-towards", "doi": ""
    },
    {
        "id": "C04", "category": "COVID-19", "study": "Egger et al. (2021)",
        "year": 2021, "source": "Science Advances", "geography": "Nine LMICs, including Bangladesh, Nepal, and the Philippines",
        "subregion": "South and Southeast Asia plus comparators", "population": "More than 30,000 households across 16 samples", "shock": "Early COVID-19 restrictions",
        "welfare_indicator": "Income, employment, food security, and market access",
        "estimate": "Income fell in 8%-87% of samples (median about 70%); employment fell 5%-49% (median 30%); 9%-87% missed or reduced meals (median 45%)",
        "methodology": "Harmonized rapid phone surveys linked to pre-pandemic samples",
        "identification": "Before-after descriptive comparisons across multiple cohorts",
        "limitations": "No unexposed control; samples and questions are heterogeneous; phone attrition may be selective",
        "confidence": "Medium", "evidence_type": "Multi-country panel survey",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7864564/", "doi": "10.1126/sciadv.abe0997"
    },
    {
        "id": "C05", "category": "COVID-19", "study": "World Bank (2021a)",
        "year": 2021, "source": "Uneven Recovery: East Asia and Pacific Economic Update", "geography": "Developing East Asia and Pacific",
        "subregion": "East Asia and Pacific", "population": "Households, children, and firms", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Poverty, learning participation, and business sales",
        "estimate": "32 million people were prevented from escaping poverty; children in the bottom two-fifths were up to 20 percentage points less likely to be engaged in learning; microenterprise sales fell about one-third",
        "methodology": "Regional macro-poverty projections and harmonized high-frequency surveys",
        "identification": "Counterfactual projection plus descriptive survey comparisons",
        "limitations": "Several estimates combine different country samples and reference periods",
        "confidence": "Medium", "evidence_type": "Regional synthesis",
        "url": "https://www.worldbank.org/en/region/eap/publication/uneven-recovery-east-asia-and-pacific-economic-update-april-2021", "doi": ""
    },
    {
        "id": "C06", "category": "COVID-19", "study": "World Bank (2021b)",
        "year": 2021, "source": "Long COVID: East Asia and Pacific Economic Update", "geography": "Developing East Asia and Pacific",
        "subregion": "East Asia and Pacific", "population": "Students", "shock": "School closures and learning disruption",
        "welfare_indicator": "Lifetime earnings",
        "estimate": "Average annual earnings loss of about $524 per student in 2017 PPP, or 3.8%; estimated loss reaches 9.3% in ASEAN-5 and 7.9% in small East Asian economies",
        "methodology": "Learning-adjusted schooling losses mapped to returns to education and lifetime earnings",
        "identification": "Simulation using closure, learning, and earnings parameters",
        "limitations": "Long-run projection; recovery, remediation, discount rates, and labour-market returns are uncertain",
        "confidence": "Medium", "evidence_type": "Human-capital simulation",
        "url": "https://documents1.worldbank.org/curated/en/138851632895977756/pdf/World-Bank-East-Asia-and-Pacific-Economic-Update-Long-COVID.pdf", "doi": ""
    },
    {
        "id": "C07", "category": "COVID-19", "study": "Yarrow et al. (2020)",
        "year": 2020, "source": "World Bank", "geography": "Indonesia",
        "subregion": "Southeast Asia", "population": "About 68 million students", "shock": "School closures",
        "welfare_indicator": "Learning and lifetime income",
        "estimate": "Roughly 0.5 year of learning or 16 PISA reading points lost; $222.4 billion in lifetime income, equivalent to 19.9% of 2019 GDP",
        "methodology": "School-closure scenarios linked to learning-adjusted years of schooling and returns to education",
        "identification": "Simulation",
        "limitations": "Assumes parameterized learning loss and persistence; not an observed earnings outcome",
        "confidence": "Medium", "evidence_type": "Human-capital simulation",
        "url": "https://www.worldbank.org/en/country/indonesia/publication/estimates-of-covid-19-impacts-on-learning-and-earning-in-indonesia-how-to-turn-the-tide", "doi": ""
    },
    {
        "id": "C08", "category": "COVID-19", "study": "World Bank (2023a)",
        "year": 2023, "source": "Collapse and Recovery: How COVID-19 Eroded Human Capital and What to Do About It", "geography": "South Asia",
        "subregion": "South Asia", "population": "Children and young people", "shock": "Pandemic-era service and school disruption",
        "welfare_indicator": "Learning poverty and future earnings",
        "estimate": "Learning poverty rose from about 60% to 78%; current students may lose up to 14.4% of future earnings; every 30 days of closure was associated with about 32 days of learning loss",
        "methodology": "Regional synthesis of assessment data, closure duration, and human-capital simulations",
        "identification": "Observed assessments plus modelled lifetime effects",
        "limitations": "Some countries lack comparable post-pandemic tests; earnings effects are projections",
        "confidence": "Medium", "evidence_type": "Regional synthesis",
        "url": "https://www.worldbank.org/en/news/press-release/2023/02/16/covid-19-s-impact-on-south-asia-s-youth-could-last-generations", "doi": ""
    },
    {
        "id": "C09", "category": "COVID-19", "study": "Osendarp et al. (2021)",
        "year": 2021, "source": "Nature Food", "geography": "118 low- and middle-income countries, with heavy burden in South Asia",
        "subregion": "Global LMIC; Asia-relevant", "population": "Children under five and women", "shock": "Pandemic income and nutrition-service disruptions",
        "welfare_indicator": "Wasting, stunting, maternal nutrition, deaths, and productivity",
        "estimate": "Moderate 2020-2022 scenario: 9.3 million additional wasted children, 2.6 million additional stunted children, 168,000 additional under-five deaths, and $29.7 billion in future productivity losses",
        "methodology": "Linked MIRAGRODEP, nutrition-risk, LiST, and Optima Nutrition models",
        "identification": "Scenario modelling",
        "limitations": "Not Asia-only; results depend on assumed income and service shocks and may overlap with other pandemic estimates",
        "confidence": "Medium", "evidence_type": "Nutrition scenario model",
        "url": "https://www.nature.com/articles/s43016-021-00319-4", "doi": "10.1038/s43016-021-00319-4"
    },
    {
        "id": "C10", "category": "COVID-19", "study": "UNICEF (2021)",
        "year": 2021, "source": "Direct and Indirect Effects of COVID-19 on South Asia", "geography": "South Asia",
        "subregion": "South Asia", "population": "Women and children", "shock": "Essential health-service disruption",
        "welfare_indicator": "Maternal and child mortality",
        "estimate": "Service disruptions may have contributed to about 228,000 additional child deaths and 11,000 additional maternal deaths in 2020",
        "methodology": "Country service-disruption scenarios combined with LiST-type mortality modelling",
        "identification": "Scenario modelling",
        "limitations": "Counterfactual is sensitive to assumed service declines and does not identify individual deaths",
        "confidence": "Medium", "evidence_type": "Health-service scenario model",
        "url": "https://www.unicef.org/press-releases/disruptions-health-services-due-covid-19-may-have-contributed-additional-239000", "doi": ""
    },
    {
        "id": "C11", "category": "COVID-19", "study": "COVID-19 Mental Disorders Collaborators (2021)",
        "year": 2021, "source": "The Lancet", "geography": "204 countries and territories, including Asia-Pacific",
        "subregion": "Global; country estimates", "population": "All ages; sex- and age-disaggregated", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Major depressive and anxiety disorders and DALYs",
        "estimate": "53.2 million additional major-depressive-disorder cases (+27.6%) and 76.2 million additional anxiety cases (+25.6%) in 2020; females and younger people bore larger increases",
        "methodology": "Systematic review and Bayesian meta-regression linked to mobility and infection indicators",
        "identification": "Model-based association using pre-post prevalence studies",
        "limitations": "Sparse direct surveys in many Asian countries; no clean separation of infection, restrictions, and recession channels",
        "confidence": "Medium", "evidence_type": "Global burden model",
        "url": "https://doi.org/10.1016/S0140-6736(21)02143-7", "doi": "10.1016/S0140-6736(21)02143-7"
    },
    {
        "id": "C12", "category": "COVID-19", "study": "COVID-19 Excess Mortality Collaborators (2022)",
        "year": 2022, "source": "The Lancet", "geography": "191 countries and territories",
        "subregion": "Global; South Asia prominent", "population": "All ages", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Excess deaths",
        "estimate": "18.2 million global excess deaths in 2020-2021 versus 5.94 million reported COVID deaths; India 4.07 million, Indonesia 736,000, Pakistan 664,000",
        "methodology": "All-cause mortality comparison plus ensemble models for data-poor locations",
        "identification": "Excess-mortality counterfactual",
        "limitations": "Only 74 countries had full mortality series; model uncertainty is substantial in data-scarce settings",
        "confidence": "Medium", "evidence_type": "Excess mortality model",
        "url": "https://doi.org/10.1016/S0140-6736(21)02796-3", "doi": "10.1016/S0140-6736(21)02796-3"
    },
    {
        "id": "C13", "category": "COVID-19", "study": "World Health Organization (2022)",
        "year": 2022, "source": "WHO global excess mortality estimates", "geography": "Global and WHO regions",
        "subregion": "Southeast Asia region included", "population": "All ages", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Excess deaths",
        "estimate": "14.9 million excess deaths in 2020-2021; 84% were concentrated in South-East Asia, Europe, and the Americas; 57% were male and mortality was concentrated among older adults",
        "methodology": "Country all-cause mortality series with covariate-based modelling where data were missing",
        "identification": "Excess-mortality counterfactual",
        "limitations": "Regional aggregation masks country variation; estimates differ from other global models",
        "confidence": "Medium", "evidence_type": "Excess mortality model",
        "url": "https://www.who.int/news/item/05-05-2022-14.9-million-excess-deaths-were-associated-with-the-covid-19-pandemic-in-2020-and-2021", "doi": ""
    },
    {
        "id": "C14", "category": "COVID-19", "study": "Kugler et al. (2023)",
        "year": 2023, "source": "World Development", "geography": "40 developing countries, including East and South Asia",
        "subregion": "Multi-region; Asia-relevant", "population": "Working-age adults", "shock": "COVID-19 labour-market disruption",
        "welfare_indicator": "Work stoppage by sex, age, education, and location",
        "estimate": "Women were 8 percentage points more likely than men to stop work; youth 4 points more likely than older adults; low-education and urban workers each about 4 and 3 points more likely",
        "methodology": "Harmonized high-frequency phone surveys with multivariate decomposition",
        "identification": "Cross-sectional conditional gaps during the crisis",
        "limitations": "Not causal treatment effects; phone samples and timing differ; country averages conceal informal-work intensity",
        "confidence": "Medium", "evidence_type": "Harmonized household surveys",
        "url": "https://doi.org/10.1016/j.worlddev.2023.106331", "doi": "10.1016/j.worlddev.2023.106331"
    },
    {
        "id": "C15", "category": "COVID-19", "study": "O'Driscoll et al. (2021)",
        "year": 2021, "source": "Nature", "geography": "45 countries with 22 seroprevalence studies",
        "subregion": "Global; age gradient transferable", "population": "All ages", "shock": "SARS-CoV-2 infection",
        "welfare_indicator": "Infection fatality ratio by age and sex",
        "estimate": "IFR rose from 0.001% at ages 5-9 to 8.29% at age 80+; among those 80+, estimated IFR was 10.83% for men and 5.76% for women",
        "methodology": "Bayesian ensemble model combining age-specific deaths and seroprevalence",
        "identification": "Epidemiological model",
        "limitations": "Pre-vaccination variants and health-system context; not a direct Asia-only welfare valuation",
        "confidence": "High", "evidence_type": "Peer-reviewed epidemiological model",
        "url": "https://www.nature.com/articles/s41586-020-2918-0", "doi": "10.1038/s41586-020-2918-0"
    },
    {
        "id": "C16", "category": "COVID-19", "study": "Asian Development Bank (2022a)",
        "year": 2022, "source": "Southeast Asia Development Symposium report", "geography": "Southeast Asia",
        "subregion": "Southeast Asia", "population": "Workers and people near extreme poverty", "shock": "COVID-19 pandemic",
        "welfare_indicator": "Jobs and extreme poverty",
        "estimate": "4.7 million additional people in extreme poverty and 9.3 million jobs lost in 2021 versus a no-COVID baseline",
        "methodology": "Regional macro-labour and poverty counterfactual",
        "identification": "Modelled baseline comparison",
        "limitations": "Does not capture non-monetary welfare or within-country distribution fully",
        "confidence": "Medium", "evidence_type": "Regional model",
        "url": "https://www.adb.org/news/covid-19-pushed-4-7-million-more-people-southeast-asia-extreme-poverty-2021-countries-are-well", "doi": ""
    },

    {
        "id": "E01", "category": "Economic shock", "study": "Headey and Ruel (2023)",
        "year": 2023, "source": "Nature Communications", "geography": "44 low- and middle-income countries, including South and Southeast Asia",
        "subregion": "Multi-region; Asia-relevant", "population": "1.27 million children under five", "shock": "Real food-price inflation",
        "welfare_indicator": "Wasting and stunting",
        "estimate": "A 5% rise in real food prices over the previous three months increased wasting risk 9% and severe wasting 14%; the increase was 15% for asset-poor children and 6% for non-poor children",
        "methodology": "DHS microdata merged with local food-price series; child, season, and location controls",
        "identification": "Within-country observational panel of repeated cross-sections",
        "limitations": "Price endogeneity and incomplete local market coverage remain; estimates are relative risks, not percentage-point changes",
        "confidence": "High", "evidence_type": "Large-sample microeconometric study",
        "url": "https://www.nature.com/articles/s41467-023-41543-9", "doi": "10.1038/s41467-023-41543-9"
    },
    {
        "id": "E02", "category": "Economic shock", "study": "International Monetary Fund (2022)",
        "year": 2022, "source": "Regional Economic Outlook: Asia and Pacific", "geography": "Selected Asian emerging and developing economies",
        "subregion": "Regional", "population": "Households by income group", "shock": "Food and energy inflation",
        "welfare_indicator": "Real income and relative poverty",
        "estimate": "Projected 2022 inflation raised relative poverty about 1 percentage point in Cambodia and Viet Nam and 0.2 point in China; a severe combined price shock roughly doubled the effects",
        "methodology": "Household-budget-incidence microsimulation using survey expenditure shares",
        "identification": "Simulated price pass-through",
        "limitations": "Short-run fixed quantities; omits some wage, producer, and substitution responses",
        "confidence": "Medium", "evidence_type": "Microsimulation",
        "url": "https://www.elibrary.imf.org/abstract/book/9798400220517/CH001.xml", "doi": ""
    },
    {
        "id": "E03", "category": "Economic shock", "study": "World Bank (2022a)",
        "year": 2022, "source": "Reforms for Recovery: East Asia and Pacific Economic Update", "geography": "Developing East Asia and Pacific",
        "subregion": "East Asia and Pacific", "population": "Households", "shock": "Cost-of-living inflation",
        "welfare_indicator": "Purchasing power",
        "estimate": "Inflation eroded household purchasing power by about 2% in Viet Nam and 11% in Mongolia across the country cases examined",
        "methodology": "Household-survey budget shares combined with observed price changes",
        "identification": "Accounting microsimulation",
        "limitations": "Static incidence; estimates are not uniform regional losses and exclude general-equilibrium adjustment",
        "confidence": "Medium", "evidence_type": "Regional microsimulation",
        "url": "https://www.worldbank.org/en/publication/reforms-for-recovery-east-asia-and-pacific-economic-update-october-2022", "doi": ""
    },
    {
        "id": "E04", "category": "Economic shock", "study": "United Nations Development Programme (2022a)",
        "year": 2022, "source": "Addressing the Cost-of-Living Crisis in Developing Countries", "geography": "159 developing countries",
        "subregion": "Global; Asian hotspots identified", "population": "People near monetary poverty lines", "shock": "Food and energy price surge",
        "welfare_indicator": "Poverty",
        "estimate": "About 71 million people could be pushed into poverty within three months; Asian hotspots included Armenia, Pakistan, Sri Lanka, and Uzbekistan",
        "methodology": "Country-level price-shock and poverty microsimulation",
        "identification": "Scenario model",
        "limitations": "Global total is not an Asia subtotal; results depend on price pass-through and poverty thresholds",
        "confidence": "Medium", "evidence_type": "Global microsimulation",
        "url": "https://www.undp.org/publications/addressing-cost-living-crisis-developing-countries-poverty-and-vulnerability-projections-and-policy-responses", "doi": ""
    },
    {
        "id": "E05", "category": "Economic shock", "study": "World Bank (2023b)",
        "year": 2023, "source": "Sri Lanka Development Update: Time to Reset", "geography": "Sri Lanka",
        "subregion": "South Asia", "population": "Households and workers", "shock": "Debt, balance-of-payments, inflation, and recession crisis",
        "welfare_indicator": "Poverty, jobs, living costs, and nutrition",
        "estimate": "Poverty rose from 13.1% in 2021 to 25.0% in 2022 at the $3.65 2017 PPP line, adding about 2.5 million poor people; an estimated half a million industry and services jobs were lost, with annual average inflation of 46.4% in 2022",
        "methodology": "Household survey nowcasting, labour indicators, and macro-poverty simulation",
        "identification": "Observed crisis period with modelled poverty update",
        "limitations": "The pandemic, policy errors, global prices, and debt crisis are jointly determined; no single-shock causal decomposition",
        "confidence": "High", "evidence_type": "Country poverty nowcast",
        "locator": "p. 14, paragraphs 15-16",
        "url": "https://documents.worldbank.org/curated/en/099052823154030000/pdf/P1795590b753e0063080da06d77c1b4cbe5.pdf", "doi": ""
    },
    {
        "id": "E06", "category": "Economic shock", "study": "World Bank (2024a)",
        "year": 2024, "source": "Lao PDR Economic Monitor and Household Welfare Monitoring", "geography": "Lao PDR",
        "subregion": "Southeast Asia", "population": "Households and workers", "shock": "Currency depreciation and high inflation",
        "welfare_indicator": "Real wages, consumption, food security, health, and education",
        "estimate": "With 39% inflation in 2023 and nominal wages up 5.7%, real wages fell about 33%; in 2024 low-income real per-capita income fell 6.9%, and 36.2% of low-income households faced moderate or severe food insecurity",
        "methodology": "Repeated nationally oriented household phone surveys plus macro price and wage data",
        "identification": "Descriptive crisis monitoring",
        "limitations": "Phone-survey representativeness and attribution among depreciation, debt, and prices. The recorded URL is a COVID-monitoring brief that does not carry the Economic Monitor's wage and income tables; the locator screen could not reach the cited figures. Source URL must be replaced before these figures are quoted (CONSTITUTION.md §2.7).",
        "confidence": "Medium", "evidence_type": "High-frequency household survey",
        "url": "https://www.worldbank.org/en/country/lao/brief/monitoring-the-impact-of-covid-19-in-lao-pdr", "doi": ""
    },
    {
        "id": "E07", "category": "Economic shock", "study": "World Bank (2017)",
        "year": 2017, "source": "Mongolia poverty update", "geography": "Mongolia",
        "subregion": "East and Central Asia", "population": "Households", "shock": "2015-2016 commodity and macroeconomic slowdown",
        "welfare_indicator": "Poverty",
        "estimate": "National poverty rose from 21.6% in 2014 to 29.6% in 2016; rural poverty increased by 10.1 percentage points",
        "methodology": "Comparable household socioeconomic surveys and official poverty methodology",
        "identification": "Before-after welfare measurement",
        "limitations": "Cannot isolate commodity prices from domestic macro policy, weather, and labour-market channels",
        "confidence": "High", "evidence_type": "Official survey estimate",
        "url": "https://www.worldbank.org/en/news/press-release/2017/10/17/2016-poverty-rate-in-mongolia-estimated-at-296-percent", "doi": ""
    },
    {
        "id": "E08", "category": "Economic shock", "study": "United Nations Development Programme (2022b)",
        "year": 2022, "source": "Afghanistan Socio-Economic Outlook", "geography": "Afghanistan",
        "subregion": "Central and West Asia", "population": "Households, workers, and women", "shock": "Political transition, aid and banking freeze, and macroeconomic collapse",
        "welfare_indicator": "GDP, poverty, food prices, and female employment",
        "estimate": "GDP contracted about 20% in 2020-2021, a one-year loss near $5 billion; the basic food basket rose about 35%; excluding women from work could cost up to $1 billion or 5% of GDP",
        "methodology": "Macroeconomic accounting and computable general equilibrium scenarios",
        "identification": "Scenario and accounting model",
        "limitations": "Exceptional data gaps and overlapping drought, conflict, sanctions, and institutional shocks",
        "confidence": "Medium", "evidence_type": "Country scenario assessment",
        "url": "https://www.undp.org/publications/afghanistan-august-2021-socio-economic-snapshot", "doi": ""
    },
    {
        "id": "E09", "category": "Economic shock", "study": "World Bank (2024b)",
        "year": 2024, "source": "Myanmar Economic Monitor and Poverty Assessment", "geography": "Myanmar",
        "subregion": "Southeast Asia", "population": "Households", "shock": "Conflict, political disruption, inflation, and economic contraction",
        "welfare_indicator": "Poverty and economic insecurity",
        "estimate": "Poverty reached 32.1%, with about 7 million more poor people than before COVID-19; GDP remained roughly 9% below its 2019 level",
        "methodology": "Household survey and macro-poverty nowcasting under constrained data access",
        "identification": "Observed crisis-period comparison",
        "limitations": "Survey coverage and official-data reliability are unusually weak; shocks cannot be cleanly separated",
        "confidence": "Low", "evidence_type": "Country nowcast",
        "url": "https://www.worldbank.org/en/news/press-release/2024/06/12/threat-to-livelihoods-deepens-as-myanmar-economic-outlook-remains-weak", "doi": ""
    },
    {
        "id": "E10", "category": "Economic shock", "study": "Chodorow-Reich et al. (2020)",
        "year": 2020, "source": "Quarterly Journal of Economics", "geography": "India",
        "subregion": "South Asia", "population": "Workers, firms, and districts", "shock": "2016 demonetization and cash shortage",
        "welfare_indicator": "Employment, night-light output, and credit",
        "estimate": "District-level cash shortages reduced employment and night-light output by at least 2 percentage points in 2016 Q4 and bank credit by about 2 points; effects dissipated over subsequent months",
        "methodology": "Cross-district instrumental variables using pre-existing currency denomination exposure",
        "identification": "Quasi-experimental IV",
        "limitations": "Captures short-run local real effects; informal transactions and broader national effects are imperfectly measured",
        "confidence": "High", "evidence_type": "Quasi-experimental study",
        "url": "https://academic.oup.com/qje/article/135/1/57/5567189", "doi": "10.1093/qje/qjz027"
    },
    {
        "id": "E11", "category": "Economic shock", "study": "Abiad et al. (2018)",
        "year": 2018, "source": "ADB Economics Working Paper", "geography": "Developing Asia with China-US trade conflict",
        "subregion": "Regional", "population": "National economies and workers through sectoral trade exposure", "shock": "Tariffs and trade conflict",
        "welfare_indicator": "GDP and employment reallocation",
        "estimate": "Tariffs implemented at the time were estimated to reduce China's GDP by about 1% over two to three years and US GDP by about 0.2%, with mixed trade-diversion gains elsewhere in developing Asia",
        "methodology": "Global trade model and multiregional input-output analysis",
        "identification": "Ex ante policy simulation",
        "limitations": "Not a household welfare model; tariff scope and retaliation evolved after publication",
        "confidence": "Medium", "evidence_type": "Trade-policy simulation",
        "url": "https://www.adb.org/publications/impact-trade-conflict-developing-asia", "doi": "10.22617/WPS189770-2"
    },
    {
        "id": "E12", "category": "Economic shock", "study": "International Monetary Fund (2019)",
        "year": 2019, "source": "IMF Annual Report trade-conflict scenario", "geography": "Global, China, and United States",
        "subregion": "Global; East Asia focal", "population": "National economies", "shock": "US-China trade conflict",
        "welfare_indicator": "Long-run GDP",
        "estimate": "The tariff conflict was estimated to lower long-run global GDP by about 0.4% ($340 billion in 2018 dollars); China's 2019 GDP level by about 1.6% and US GDP by about 1%",
        "methodology": "IMF global macroeconomic model scenario",
        "identification": "Ex ante simulation",
        "limitations": "GDP effects are not distributional welfare and are sensitive to policy assumptions and trade diversion",
        "confidence": "Medium", "evidence_type": "Macroeconomic simulation",
        "url": "https://www.imf.org/external/pubs/ft/ar/2019/eng/spotlight/making-the-case-for-trade/index.htm", "doi": ""
    },

    {
        "id": "N01", "category": "Environmental/climate shock", "study": "Hallegatte et al. (2017)",
        "year": 2017, "source": "World Bank, Unbreakable", "geography": "117 countries, including Asia-Pacific",
        "subregion": "Global; country estimates", "population": "Households differentiated by income and resilience", "shock": "Natural disasters",
        "welfare_indicator": "Consumption-equivalent wellbeing and poverty",
        "estimate": "$520 billion in annual global consumption-equivalent wellbeing losses and 26 million people pushed into extreme poverty each year; resilience policies could cut wellbeing losses about 20%",
        "methodology": "Asset-loss risk model linked to household consumption, vulnerability, and coping capacity",
        "identification": "Ex ante welfare-risk model",
        "limitations": "Global headline is not an Asia subtotal; depends on resilience and consumption-smoothing assumptions",
        "confidence": "Medium", "evidence_type": "Welfare-risk model",
        "url": "https://documents1.worldbank.org/curated/en/512241480487839624/pdf/Unbreakable-building-the-resilience-of-the-poor-in-the-face-of-natural-disasters.pdf", "doi": ""
    },
    {
        "id": "N02", "category": "Environmental/climate shock", "study": "Asian Development Bank (2024)",
        "year": 2024, "source": "Asia-Pacific Climate Report 2024", "geography": "Developing Asia and the Pacific",
        "subregion": "Regional", "population": "Regional economies and exposed populations", "shock": "Long-run climate change",
        "welfare_indicator": "GDP, labour productivity, coastal assets, and poverty risk",
        "estimate": "Under a high-end emissions pathway, regional GDP could be 17% lower by 2070 and 41% lower by 2100; a Paris-aligned pathway limits the 2100 loss to around 11%; up to 300 million people face coastal-inundation risk",
        "methodology": "Integrated sectoral damage modelling with macroeconomic aggregation",
        "identification": "Long-run scenario comparison",
        "limitations": "Deep uncertainty in climate, adaptation, tipping points, and damage functions; not a forecast. The recorded URL is the report's landing page, not the report PDF; the US$300 billion adaptation-finance figure could not be located in reachable text. Source URL must be replaced before that figure is quoted (CONSTITUTION.md §2.7).",
        "confidence": "Medium", "evidence_type": "Integrated assessment scenario",
        "url": "https://www.adb.org/climate-report/editions/2024", "doi": ""
    },
    {
        "id": "N03", "category": "Environmental/climate shock", "study": "ESCAP (2023)",
        "year": 2023, "source": "Asia-Pacific Disaster Report 2023", "geography": "Asia and the Pacific",
        "subregion": "Regional", "population": "Regional population and assets", "shock": "Multi-hazard disasters under warming",
        "welfare_indicator": "Annualized disaster losses",
        "estimate": "At 1.5 degrees C warming, annualized losses could reach $953 billion or 3.0% of regional GDP; at 2 degrees C they approach $1 trillion or 3.1%",
        "methodology": "Probabilistic multi-hazard risk modelling",
        "identification": "Scenario risk assessment",
        "limitations": "Primarily asset/output risk rather than full household welfare; tail risks and adaptation are uncertain",
        "confidence": "Medium", "evidence_type": "Probabilistic risk model",
        "url": "https://www.unescap.org/kp/2023/asia-pacific-disaster-report-2023", "doi": ""
    },
    {
        "id": "N04", "category": "Environmental/climate shock", "study": "World Bank (2025)",
        "year": 2025, "source": "East Asia and Pacific Economic Update climate analysis", "geography": "Viet Nam and Pacific atoll economies",
        "subregion": "Southeast Asia and Pacific", "population": "National populations and coastal communities", "shock": "Climate change and tropical cyclones",
        "welfare_indicator": "GDP and disaster damage",
        "estimate": "Without adaptation, Viet Nam's GDP could be 12%-14.5% lower by 2050, with $400-$523 billion cumulative losses; current cyclone losses average about 0.8% of GDP annually; in atoll economies annual disaster losses already reach 3%-7% of GDP",
        "methodology": "Country climate and development models plus catastrophe-risk estimates",
        "identification": "Scenario and risk modelling",
        "limitations": "Combines different models, horizons, and countries; adaptation assumptions drive results",
        "confidence": "Medium", "evidence_type": "Regional scenario synthesis",
        "url": "https://documents1.worldbank.org/curated/en/099060225123042542/pdf/P507415-4906ec00-764d-4ab1-9c19-01903aec0692.pdf", "doi": ""
    },
    {
        "id": "N05", "category": "Environmental/climate shock", "study": "Mani et al. (2018)",
        "year": 2018, "source": "World Bank, South Asia's Hotspots", "geography": "India",
        "subregion": "South Asia", "population": "District populations", "shock": "Long-term temperature and precipitation change",
        "welfare_indicator": "GDP and living standards",
        "estimate": "In a carbon-intensive scenario, climate change could reduce India's GDP by 2.8% and depress living standards for nearly half its population by 2050",
        "methodology": "Spatial panel relationships between climate and living standards combined with climate scenarios",
        "identification": "Historical association projected under scenarios",
        "limitations": "Reduced-form projection; adaptation and structural transformation are difficult to model",
        "confidence": "Medium", "evidence_type": "Spatial climate-economy model",
        "url": "https://www.worldbank.org/en/news/press-release/2018/06/28/climate-change-depress-living-standards-india-says-new-world-bank-report", "doi": ""
    },
    {
        "id": "N06", "category": "Environmental/climate shock", "study": "Burke, Hsiang, and Miguel (2015)",
        "year": 2015, "source": "Nature", "geography": "Global panel with Asia-Pacific countries",
        "subregion": "Global; Asia-relevant", "population": "National economies", "shock": "Long-run warming",
        "welfare_indicator": "Income per capita",
        "estimate": "Unmitigated warming was estimated to make global income about 23% lower in 2100 than in a world without climate change",
        "methodology": "Nonlinear country-panel temperature-growth estimates projected through climate and socioeconomic scenarios",
        "identification": "Reduced-form panel association with country and year effects",
        "limitations": "Long-horizon extrapolation, adaptation, conflict with some structural models, and uncertainty around cumulative growth effects",
        "confidence": "Medium", "evidence_type": "Peer-reviewed reduced-form projection",
        "url": "https://www.nature.com/articles/nature15725", "doi": "10.1038/nature15725"
    },
    {
        "id": "N07", "category": "Environmental/climate shock", "study": "Diffenbaugh and Burke (2019)",
        "year": 2019, "source": "Proceedings of the National Academy of Sciences", "geography": "Global, with country results for Asia",
        "subregion": "Global; Asia country estimates", "population": "National populations", "shock": "Historical anthropogenic warming, 1961-2010",
        "welfare_indicator": "GDP per capita and between-country inequality",
        "estimate": "Warming increased population-weighted between-country inequality by about 25%; per-capita GDP was reduced 17%-31% at the poorest four deciles of the population-weighted country distribution, and the 18 countries with the lowest cumulative per-capita emissions had a median impact of about -27% relative to a no-warming counterfactual",
        "methodology": "Detection-and-attribution climate simulations combined with nonlinear temperature-growth response",
        "identification": "Historical climate-attribution counterfactual",
        "limitations": "Depends on contested growth response and cumulative counterfactual; estimates are not household consumption losses. The previously recorded country figures (31% India, 27% Indonesia, 12% Bangladesh) are not supported by this paper: Indonesia and Bangladesh appear nowhere in its text, and the 31% and 27% figures are a decile range and a low-emitter median respectively, not country estimates (CONSTITUTION.md §2.7)",
        "confidence": "Medium", "evidence_type": "Attribution model",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6525504/", "doi": "10.1073/pnas.1816020116"
    },
    {
        "id": "N08", "category": "Environmental/climate shock", "study": "Carleton et al. (2022)",
        "year": 2022, "source": "Quarterly Journal of Economics", "geography": "Global, including India and Asia-Pacific",
        "subregion": "Global; subnational", "population": "All ages", "shock": "Extreme heat under climate change",
        "welfare_indicator": "Mortality and monetized mortality risk",
        "estimate": "Under high emissions, net mortality costs including adaptation were valued at about 3.2% of global GDP in 2100; the mortality partial social cost of carbon was $36.6 per tCO2",
        "methodology": "Subnational mortality-temperature panel, age-specific response, adaptation, and valuation model",
        "identification": "Reduced-form panel plus forward projection",
        "limitations": "Covers mortality only; value-of-statistical-life and adaptation assumptions are consequential",
        "confidence": "High", "evidence_type": "Peer-reviewed econometric projection",
        "url": "https://academic.oup.com/qje/article/137/4/2037/6571943", "doi": "10.1093/qje/qjac020"
    },
    {
        "id": "N09", "category": "Environmental/climate shock", "study": "Vicedo-Cabrera et al. (2021)",
        "year": 2021, "source": "Nature Climate Change", "geography": "732 locations in 43 countries, including nine Asian countries",
        "subregion": "Global; Asia sites", "population": "Urban populations", "shock": "Observed anthropogenic warming",
        "welfare_indicator": "Heat-related mortality",
        "estimate": "About 37% of warm-season heat-related deaths were attributable to anthropogenic climate change in 1991-2018; estimates across included Asian countries ranged roughly from 21.3% in China to 67.7% in Kuwait",
        "methodology": "Multi-country time-series exposure-response models with climate-model attribution",
        "identification": "Detection and attribution",
        "limitations": "City coverage is uneven and rural exposure is underrepresented; results are shares of heat deaths, not all deaths",
        "confidence": "High", "evidence_type": "Peer-reviewed health attribution",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7611104/", "doi": "10.1038/s41558-021-01058-x"
    },
    {
        "id": "N10", "category": "Environmental/climate shock", "study": "Somanathan et al. (2021)",
        "year": 2021, "source": "Journal of Political Economy", "geography": "India",
        "subregion": "South Asia", "population": "Manufacturing workers and plants", "shock": "High temperatures",
        "welfare_indicator": "Worker productivity, absenteeism, and plant output",
        "estimate": "Annual plant output fell about 2% per 1 degree C increase; daily microdata show lower worker productivity and greater absenteeism, with climate control mitigating losses",
        "methodology": "Worker-level production records and national plant panels with weather variation",
        "identification": "Reduced-form panel using short-run temperature fluctuations",
        "limitations": "Selected firms for worker microdata; results may not generalize to all sectors or adaptation margins",
        "confidence": "High", "evidence_type": "Peer-reviewed microeconometric study",
        "url": "https://www.journals.uchicago.edu/doi/10.1086/713733", "doi": "10.1086/713733"
    },
    {
        "id": "N11", "category": "Environmental/climate shock", "study": "Im, Pal, and Eltahir (2017)",
        "year": 2017, "source": "Science Advances", "geography": "South Asia",
        "subregion": "South Asia", "population": "Populations of the Indus and Ganges basins", "shock": "Future humid heat",
        "welfare_indicator": "Exposure to dangerous and potentially unsurvivable wet-bulb temperatures",
        "estimate": "Under business-as-usual emissions, late-century extremes approach or exceed the 35 degrees C survivability threshold; about 4% of South Asia's population could face exceedances and roughly 75% could face dangerous wet-bulb temperatures above 31 degrees C",
        "methodology": "High-resolution regional climate modelling",
        "identification": "Climate scenario projection",
        "limitations": "Exposure is not realized mortality or income loss; thresholds, behaviour, migration, and cooling access matter",
        "confidence": "Medium", "evidence_type": "Climate exposure projection",
        "url": "https://www.science.org/doi/10.1126/sciadv.1603322", "doi": "10.1126/sciadv.1603322"
    },
    {
        "id": "N12", "category": "Environmental/climate shock", "study": "Rentschler, Salhab, and Jafino (2022)",
        "year": 2022, "source": "Nature Communications", "geography": "188 countries",
        "subregion": "Global; South and East Asia dominant", "population": "Population exposed to 1-in-100-year floods", "shock": "Fluvial, pluvial, and coastal flood risk",
        "welfare_indicator": "Flood exposure by poverty status",
        "estimate": "1.81 billion people were directly exposed globally; 1.24 billion lived in South and East Asia, including 395 million in China and 390 million in India; 170 million exposed people lived in extreme poverty",
        "methodology": "High-resolution flood maps overlaid with population and subnational poverty surfaces",
        "identification": "Exposure mapping",
        "limitations": "Exposure is not expected loss; defenses, depth, duration, coping, and actual event probability vary",
        "confidence": "High", "evidence_type": "Geospatial exposure assessment",
        "url": "https://www.nature.com/articles/s41467-022-30727-4", "doi": "10.1038/s41467-022-30727-4"
    },
    {
        "id": "N13", "category": "Environmental/climate shock", "study": "Tellman et al. (2021)",
        "year": 2021, "source": "Nature", "geography": "913 large floods in 169 countries",
        "subregion": "Global; large increases in South and Southeast Asia", "population": "People in observed flood footprints", "shock": "Floods, 2000-2018",
        "welfare_indicator": "Population directly affected and growth of exposure",
        "estimate": "Between 255 million and 290 million people were directly affected; the share of global population in observed flood footprints grew about 20%-24% from 2000 to 2015",
        "methodology": "12,719 daily MODIS images at 250-m resolution linked to population grids",
        "identification": "Remote-sensing event measurement",
        "limitations": "Cloud cover, satellite era, and event selection; exposure does not equal income, health, or consumption loss",
        "confidence": "High", "evidence_type": "Remote-sensing study",
        "url": "https://www.nature.com/articles/s41586-021-03695-w", "doi": "10.1038/s41586-021-03695-w"
    },
    {
        "id": "N14", "category": "Environmental/climate shock", "study": "Government of Pakistan et al. (2022)",
        "year": 2022, "source": "Pakistan Floods 2022 Post-Disaster Needs Assessment", "geography": "Pakistan",
        "subregion": "South Asia", "population": "33 million affected people", "shock": "2022 monsoon floods",
        "welfare_indicator": "Damage, economic losses, poverty, and multidimensional poverty",
        "estimate": "$14.9 billion in damage and $15.2 billion in economic losses; poverty projected to rise 3.7-4.0 percentage points, adding 8.4-9.1 million poor people; 1,730 deaths",
        "methodology": "Sectoral PDNA, household exposure, and macro-poverty simulation",
        "identification": "Post-disaster accounting and modelled human impact",
        "limitations": "Rapid assessment; indirect and long-run health, learning, and displacement losses are incomplete",
        "confidence": "High", "evidence_type": "Post-disaster needs assessment",
        "url": "https://documents.worldbank.org/en/publication/documents-reports/documentdetail/099910201032325572", "doi": ""
    },
    {
        "id": "N15", "category": "Environmental/climate shock", "study": "Government of Nepal (2015)",
        "year": 2015, "source": "Nepal Earthquake Post-Disaster Needs Assessment", "geography": "Nepal",
        "subregion": "South Asia", "population": "About 8 million affected people", "shock": "2015 earthquakes",
        "welfare_indicator": "Deaths, damage, economic loss, recovery need, and poverty",
        "estimate": "Over 8,790 casualties and 22,300 injuries, with the lives of about 8 million people affected; total recovery needs of US$6.7 billion; World Bank simulations project an additional 2.5-3.5 percent of Nepalis pushed into poverty in FY 2015-2016, translating into at least 700,000 additional poor",
        "methodology": "Sector-by-sector PDNA and poverty simulation",
        "identification": "Post-disaster accounting",
        "limitations": "Rapid assessment and simultaneous trade disruption; asset damage is not consumption-equivalent welfare. The widely cited US$5.15 billion damage / US$1.9 billion loss split is not carried in Volume A: Key Findings, which reports total recovery needs instead; that split requires the volume that carries it before it may be quoted",
        "confidence": "High", "evidence_type": "Post-disaster needs assessment",
        "locator": "Vol. A: Key Findings, pp. 13, 18, 22-23",
        "url": "https://www.worldbank.org/content/dam/Worldbank/document/SAR/nepal/PDNA%20Volume%20A%20Final.pdf", "doi": ""
    },
    {
        "id": "N16", "category": "Environmental/climate shock", "study": "Government of Vanuatu (2015)",
        "year": 2015, "source": "Tropical Cyclone Pam Post-Disaster Needs Assessment", "geography": "Vanuatu",
        "subregion": "Pacific", "population": "National population; rural livelihoods", "shock": "Tropical Cyclone Pam",
        "welfare_indicator": "Damage and economic loss",
        "estimate": "About $450 million in damage and losses, equivalent to 64% of GDP; roughly 65,000 people displaced and livelihoods of at least 80% of the rural population compromised",
        "methodology": "Sectoral PDNA",
        "identification": "Post-disaster accounting",
        "limitations": "GDP ratio is a flow-stock comparison and does not measure distribution or lifetime welfare. The recorded URL is a 2024 World Bank results story, not the 2015 Post-Disaster Needs Assessment it cites; the displacement and rural-livelihood figures could not be located. Source URL must be replaced before these figures are quoted (CONSTITUTION.md §2.7).",
        "confidence": "High", "evidence_type": "Post-disaster needs assessment",
        "url": "https://www.worldbank.org/en/results/2024/06/07/improving-lives-and-building-resilience-in-vanuatu", "doi": ""
    },
    {
        "id": "N17", "category": "Environmental/climate shock", "study": "Government of Fiji (2016)",
        "year": 2016, "source": "Tropical Cyclone Winston Post-Disaster Needs Assessment", "geography": "Fiji",
        "subregion": "Pacific", "population": "National population", "shock": "Tropical Cyclone Winston",
        "welfare_indicator": "Deaths, damage and economic loss, housing",
        "estimate": "44 deaths and about $1.38 billion in damage and losses, equivalent to 31% of GDP; 30,369 houses were damaged or destroyed and about 62% of the population was affected",
        "methodology": "Sectoral PDNA",
        "identification": "Post-disaster accounting",
        "limitations": "Reported totals vary with currency and definition; non-market and long-run wellbeing losses are incomplete",
        "confidence": "High", "evidence_type": "Post-disaster needs assessment",
        "url": "https://www.worldbank.org/en/news/press-release/2016/06/30/world-bank-commits-50m-to-support-fijis-long-term-cyclone-winston-recovery", "doi": ""
    },
    {
        "id": "N18", "category": "Environmental/climate shock", "study": "World Bank (2022b)",
        "year": 2022, "source": "Tonga Hunga Tonga-Hunga Ha'apai GRADE assessment", "geography": "Tonga",
        "subregion": "Pacific", "population": "National population", "shock": "Volcanic eruption, tsunami, and ashfall",
        "welfare_indicator": "Direct physical damage",
        "estimate": "$90.4 million in direct damage, equivalent to about 18.5% of GDP",
        "methodology": "Remote Global Rapid Post-Disaster Damage Estimation",
        "identification": "Post-event damage model",
        "limitations": "Excluded indirect economic losses and uncertain future ashfall and clean-up costs",
        "confidence": "Medium", "evidence_type": "Rapid damage assessment",
        "url": "https://www.worldbank.org/en/news/press-release/2022/02/14/tonga-volcanic-eruption-and-tsunami-world-bank-disaster-assessment-report-estimates-damages-at-us-90m", "doi": ""
    },
    {
        "id": "N19", "category": "Environmental/climate shock", "study": "Groppo and Kraehnert (2016)",
        "year": 2016, "source": "World Development", "geography": "Mongolia",
        "subregion": "East and Central Asia", "population": "Young children in herding households", "shock": "2009-2010 dzud",
        "welfare_indicator": "Child height-for-age",
        "estimate": "Children exposed in utero or infancy in severely affected districts had height-for-age z-scores about 1.67 standard deviations lower in the preferred interaction estimate; 10.3 million livestock died",
        "methodology": "Two-wave child panel exploiting spatial and cohort variation in dzud intensity",
        "identification": "Difference-in-differences-style exposure design",
        "limitations": "Relatively small exposed sample and a single exceptional event; external validity beyond herding households is limited",
        "confidence": "Medium", "evidence_type": "Quasi-experimental child panel",
        "url": "https://doi.org/10.1016/j.worlddev.2016.05.005", "doi": "10.1016/j.worlddev.2016.05.005"
    },
    {
        "id": "N20", "category": "Environmental/climate shock", "study": "Skoufias et al. (2013)",
        "year": 2013, "source": "World Bank, Disquiet on the Weather Front", "geography": "Rural Philippines",
        "subregion": "Southeast Asia", "population": "Rural households", "shock": "Drought and rainfall variability",
        "welfare_indicator": "Income and food consumption",
        "estimate": "Drought exposure reduced household food consumption by about 4%",
        "methodology": "Family Income and Expenditure Surveys for 2003, 2006, and 2009 matched to 43 rainfall stations",
        "identification": "Repeated cross-section weather-shock regressions",
        "limitations": "Pre-2015 events retained for mechanism evidence; rainfall measurement and household adaptation are imperfect",
        "confidence": "Medium", "evidence_type": "Household-weather econometrics",
        "url": "https://www.worldbank.org/en/country/philippines/publication/disquiet-on-the-weather-front-the-welfare-impacts-of-climatic-variability-in-the-rural-philippines", "doi": ""
    },
    {
        "id": "N21", "category": "Environmental/climate shock", "study": "India State-Level Disease Burden Initiative Air Pollution Collaborators (2021)",
        "year": 2021, "source": "The Lancet Planetary Health", "geography": "India",
        "subregion": "South Asia", "population": "All ages", "shock": "Ambient and household air pollution",
        "welfare_indicator": "Deaths, disease burden, and output loss",
        "estimate": "1.67 million deaths in 2019 (17.8% of all deaths) were attributable to air pollution; output losses were $36.8 billion, or 1.36% of GDP",
        "methodology": "Global Burden of Disease comparative risk assessment plus labour-output valuation",
        "identification": "Risk-attribution and economic accounting",
        "limitations": "Not an event shock; exposure-response and monetization uncertainty; excludes full willingness-to-pay welfare",
        "confidence": "High", "evidence_type": "Burden-of-disease study",
        "url": "https://doi.org/10.1016/S2542-5196(20)30298-9", "doi": "10.1016/S2542-5196(20)30298-9"
    },
    {
        "id": "N22", "category": "Environmental/climate shock", "study": "Ebenstein et al. (2017)",
        "year": 2017, "source": "Proceedings of the National Academy of Sciences", "geography": "China",
        "subregion": "East Asia", "population": "Northern and southern Chinese populations", "shock": "Long-term particulate pollution induced by the Huai River heating policy",
        "welfare_indicator": "Life expectancy",
        "estimate": "A 10 microgram/m3 increase in PM10 reduced life expectancy by about 0.64 year; meeting China's Class I standard was estimated to save 3.7 billion life-years",
        "methodology": "Regression discontinuity/instrumental variables at the Huai River policy boundary",
        "identification": "Quasi-experimental spatial discontinuity",
        "limitations": "Policy-era pollution mix and mortality response may not transfer directly to current PM2.5 or other countries",
        "confidence": "High", "evidence_type": "Quasi-experimental study",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5625887/", "doi": "10.1073/pnas.1616784114"
    },
    {
        "id": "N23", "category": "Environmental/climate shock", "study": "Koplitz et al. (2016)",
        "year": 2016, "source": "Environmental Research Letters", "geography": "Indonesia, Malaysia, and Singapore",
        "subregion": "Southeast Asia", "population": "Populations exposed to smoke", "shock": "2015 peat and forest-fire haze",
        "welfare_indicator": "Premature mortality from PM2.5 exposure",
        "estimate": "About 100,300 premature deaths were estimated across the three countries, more than 90,000 in Indonesia",
        "methodology": "Fire-emissions, atmospheric transport, exposure, and concentration-response model",
        "identification": "Event-attribution model",
        "limitations": "Modelled mortality is far above contemporaneous reported acute deaths; emissions and exposure-response uncertainty is material",
        "confidence": "Medium", "evidence_type": "Atmospheric health-impact model",
        "url": "https://doi.org/10.1088/1748-9326/11/9/094023", "doi": "10.1088/1748-9326/11/9/094023"
    },
    {
        "id": "N24", "category": "Environmental/climate shock", "study": "Johnston et al. (2021)",
        "year": 2021, "source": "Nature Sustainability", "geography": "Eastern Australia",
        "subregion": "Developed Asia-Pacific comparator", "population": "Populations exposed to 2019-2020 bushfire smoke", "shock": "Black Summer megafire smoke",
        "welfare_indicator": "Premature deaths, hospital use, and health costs",
        "estimate": "Smoke exposure was associated with 417 excess deaths, 1,124 cardiovascular and 2,027 respiratory hospital admissions, 1,305 asthma emergency visits, and A$1.95 billion in health costs",
        "methodology": "Daily PM2.5 exposure attribution, epidemiological concentration-response functions, and economic valuation",
        "identification": "Event-attribution and cost-of-illness model",
        "limitations": "Health-cost valuation excludes ecosystem, housing, mental-health, and long-term morbidity losses",
        "confidence": "High", "evidence_type": "Peer-reviewed health valuation",
        "url": "https://www.nature.com/articles/s41893-020-00610-5", "doi": "10.1038/s41893-020-00610-5"
    },
    {
        "id": "N25", "category": "Environmental/climate shock", "study": "Banerjee and Maharaj (2019)",
        "year": 2019, "source": "Journal of Development Economics", "geography": "Rural India",
        "subregion": "South Asia", "population": "Infants exposed in utero", "shock": "Extreme heat during pregnancy",
        "welfare_indicator": "Infant mortality",
        "estimate": "About 2 additional children die as infants per 1,000 births following high temperature during pregnancy; the relationship holds in rural India only",
        "methodology": "Temperature exposure during gestation linked to infant survival, with phased programme rollout used for identification",
        "identification": "Quasi-experimental; employment-guarantee and community-health-worker rollouts exploited as adaptation margins",
        "limitations": "Mechanism is inferred rather than directly measured (reduced yields, wages, and diarrhoeal disease); the estimate is rural and may not transfer to urban exposure. Only the health-worker programme modified the temperature-mortality relationship; the employment guarantee did not",
        "confidence": "High", "evidence_type": "Quasi-experimental cohort",
        "locator": "accepted manuscript p. 1 (abstract)",
        "url": "https://uoe.figshare.com/articles/Heat_infant_mortality_and_adaptation_Evidence_from_India/29762129",
        "doi": "10.1016/j.jdeveco.2019.102378"
    },
    {
        "id": "N26", "category": "Environmental/climate shock", "study": "Tiwari, Jacoby, and Skoufias (2016)",
        "year": 2016, "source": "Economic Development and Cultural Change", "geography": "Rural Nepal",
        "subregion": "South Asia", "population": "Children aged 0-60 months", "shock": "Monsoon rainfall shocks",
        "welfare_indicator": "Child weight-for-height and height",
        "estimate": "A 10% increase in monsoon rainfall above historic norms raises weight-for-height by 0.13 standard deviations, combining a negative disease-environment effect of at most 0.04 SD with an income effect as high as 0.17 SD; the height gain is transitory and dissipates by age 5",
        "methodology": "Rainfall-shock timing interacted with agricultural seasonality to isolate income from disease channels",
        "identification": "Quasi-experimental use of monsoon timing",
        "limitations": "Identifies the income channel for a rainfall surplus rather than a drought deficit; the height effect is explicitly transitory, so this record does not support a long-run human-capital claim",
        "confidence": "High", "evidence_type": "Quasi-experimental anthropometric study",
        "locator": "abstract",
        "url": "https://doi.org/10.1086/689308", "doi": "10.1086/689308"
    },
    {
        "id": "N27", "category": "Environmental/climate shock", "study": "Giannelli and Canessa (2021)",
        "year": 2021, "source": "Economic Development and Cultural Change", "geography": "Rural Bangladesh",
        "subregion": "South Asia", "population": "Rural households across the wealth distribution", "shock": "August-September 2014 flood",
        "welfare_indicator": "Income, expenditure, nutrition, and migration",
        "estimate": "Most-affected households saw significant drops in income and expenditure; internal migration rose 7 percentage points among low-wealth households and international migration 3 points among high-wealth households; remittances to poorer households offset roughly 40% of the decline in farm self-employment income and half the decline in food expenditure",
        "methodology": "Georeferenced flood mapping matched to a household panel; difference-in-differences with fixed effects",
        "identification": "Difference-in-differences on geographic flood exposure",
        "limitations": "Coping capacity is stratified by pre-shock wealth, so the averages conceal that the poorest substitute internal migration for the international migration only wealthier households can afford",
        "confidence": "High", "evidence_type": "Quasi-experimental household panel",
        "locator": "abstract",
        "url": "https://doi.org/10.1086/713939", "doi": "10.1086/713939"
    },
]


REFERENCES = [
    "Abiad, A., Arao, R. M., Dagli, S., Ferrarini, B., Noy, I., Osewe, P. L., Pagaduan, J., Park, D., and Platitas, R. (2021). The economic impact of the COVID-19 outbreak on developing Asia. In Macroeconomic Impact of COVID-19 in Developing Asia. Asian Development Bank.",
    "Abiad, A., Baris, K., Bernabe, J. A., Bertulfo, D. J., Camingue-Romance, S., Feliciano, P. N., Mariasingham, M. J., and Mercer-Blackman, V. (2018). The Impact of Trade Conflict on Developing Asia. ADB Economics Working Paper No. 566. https://doi.org/10.22617/WPS189770-2",
    "Asian Development Bank. (2021a). Macroeconomic Impact of COVID-19 in Developing Asia. Manila: ADB.",
    "Asian Development Bank. (2021b). Key Indicators for Asia and the Pacific 2021. Manila: ADB.",
    "Asian Development Bank. (2022a). Southeast Asia Rising from the Pandemic. Manila: ADB.",
    "Asian Development Bank. (2024). Asia-Pacific Climate Report 2024: Catalyzing Finance and Policy Solutions. Manila: ADB.",
    "Burke, M., Hsiang, S. M., and Miguel, E. (2015). Global non-linear effect of temperature on economic production. Nature, 527, 235-239. https://doi.org/10.1038/nature15725",
    "Carleton, T., Jina, A., Delgado, M., Greenstone, M., Houser, T., Hsiang, S., Hultgren, A., Kopp, R. E., McCusker, K. E., Nath, I., Rising, J., Rode, A., Seo, H. K., Viaene, A., Yuan, J., and Zhang, A. T. (2022). Valuing the global mortality consequences of climate change accounting for adaptation costs and benefits. Quarterly Journal of Economics, 137(4), 2037-2105. https://doi.org/10.1093/qje/qjac020",
    "Chodorow-Reich, G., Gopinath, G., Mishra, P., and Narayanan, A. (2020). Cash and the economy: Evidence from India's demonetization. Quarterly Journal of Economics, 135(1), 57-103. https://doi.org/10.1093/qje/qjz027",
    "COVID-19 Excess Mortality Collaborators. (2022). Estimating excess mortality due to the COVID-19 pandemic: A systematic analysis of COVID-19-related mortality, 2020-21. The Lancet, 399, 1513-1536. https://doi.org/10.1016/S0140-6736(21)02796-3",
    "COVID-19 Mental Disorders Collaborators. (2021). Global prevalence and burden of depressive and anxiety disorders in 204 countries and territories in 2020 due to the COVID-19 pandemic. The Lancet, 398, 1700-1712. https://doi.org/10.1016/S0140-6736(21)02143-7",
    "Diffenbaugh, N. S., and Burke, M. (2019). Global warming has increased global economic inequality. Proceedings of the National Academy of Sciences, 116(20), 9808-9813. https://doi.org/10.1073/pnas.1816020116",
    "Ebenstein, A., Fan, M., Greenstone, M., He, G., and Zhou, M. (2017). New evidence on the impact of sustained exposure to air pollution on life expectancy from China's Huai River Policy. Proceedings of the National Academy of Sciences, 114(39), 10384-10389. https://doi.org/10.1073/pnas.1616784114",
    "Egger, D., Miguel, E., Warren, S. S., Shenoy, A., Collins, E., Karlan, D., Parkerson, D., et al. (2021). Falling living standards during the COVID-19 crisis: Quantitative evidence from nine developing countries. Science Advances, 7(6), eabe0997. https://doi.org/10.1126/sciadv.abe0997",
    "ESCAP. (2023). Asia-Pacific Disaster Report 2023: Seizing the Moment. Bangkok: United Nations Economic and Social Commission for Asia and the Pacific.",
    "Government of Fiji. (2016). Fiji Post-Disaster Needs Assessment: Tropical Cyclone Winston. Suva.",
    "Government of Nepal, National Planning Commission. (2015). Nepal Earthquake 2015: Post Disaster Needs Assessment. Kathmandu.",
    "Government of Pakistan, Asian Development Bank, European Union, United Nations, and World Bank. (2022). Pakistan Floods 2022: Post-Disaster Needs Assessment. Islamabad.",
    "Government of Vanuatu. (2015). Vanuatu Post-Disaster Needs Assessment: Tropical Cyclone Pam. Port Vila.",
    "Groppo, V., and Kraehnert, K. (2016). Extreme weather events and child height: Evidence from Mongolia. World Development, 86, 59-78. https://doi.org/10.1016/j.worlddev.2016.07.005",
    "Hallegatte, S., Vogt-Schilb, A., Bangalore, M., and Rozenberg, J. (2017). Unbreakable: Building the Resilience of the Poor in the Face of Natural Disasters. Washington, DC: World Bank.",
    "Headey, D., and Ruel, M. (2023). Food inflation and child undernutrition in low and middle income countries. Nature Communications, 14, 5761. https://doi.org/10.1038/s41467-023-41543-9",
    "Im, E.-S., Pal, J. S., and Eltahir, E. A. B. (2017). Deadly heat waves projected in the densely populated agricultural regions of South Asia. Science Advances, 3(8), e1603322. https://doi.org/10.1126/sciadv.1603322",
    "India State-Level Disease Burden Initiative Air Pollution Collaborators. (2021). Health and economic impact of air pollution in the states of India: The Global Burden of Disease Study 2019. The Lancet Planetary Health, 5(1), e25-e38. https://doi.org/10.1016/S2542-5196(20)30298-9",
    "International Labour Organization. (2020). Asia-Pacific Employment and Social Outlook 2020: Navigating the Crisis towards a Human-Centred Future of Work. Bangkok: ILO.",
    "International Monetary Fund. (2019). Making the case for trade. IMF Annual Report 2019. Washington, DC: IMF.",
    "International Monetary Fund. (2022). Regional Economic Outlook: Asia and Pacific - Sailing into Headwinds. Washington, DC: IMF.",
    "Johnston, F. H., Borchers-Arriagada, N., Morgan, G. G., Jalaludin, B., Palmer, A. J., Williamson, G. J., and Bowman, D. M. J. S. (2021). Unprecedented health costs of smoke-related PM2.5 from the 2019-20 Australian megafires. Nature Sustainability, 4, 42-47. https://doi.org/10.1038/s41893-020-00610-5",
    "Koplitz, S. N., Mickley, L. J., Marlier, M. E., Buonocore, J. J., Kim, P. S., Liu, T., Sulprizio, M. P., DeFries, R. S., Jacob, D. J., Schwartz, J., Pongsiri, M., and Myers, S. S. (2016). Public health impacts of the severe haze in Equatorial Asia in September-October 2015. Environmental Research Letters, 11(9), 094023. https://doi.org/10.1088/1748-9326/11/9/094023",
    "Kugler, M., Viollaz, M., Duque, D., Gaddis, I., Newhouse, D., Palacios-Lopez, A., and Weber, M. (2023). How did the COVID-19 crisis affect different types of workers in the developing world? World Development, 170, 106331. https://doi.org/10.1016/j.worlddev.2023.106331",
    "Mani, M., Bandyopadhyay, S., Chonabayashi, S., Markandya, A., and Mosier, T. (2018). South Asia's Hotspots: The Impact of Temperature and Precipitation Changes on Living Standards. Washington, DC: World Bank.",
    "O'Driscoll, M., Ribeiro Dos Santos, G., Wang, L., Cummings, D. A. T., Azman, A. S., Paireau, J., Fontanet, A., Cauchemez, S., and Salje, H. (2021). Age-specific mortality and immunity patterns of SARS-CoV-2. Nature, 590, 140-145. https://doi.org/10.1038/s41586-020-2918-0",
    "Osendarp, S., Akuoku, J. K., Black, R. E., Headey, D., Ruel, M., Scott, N., Shekar, M., Walker, N., Flory, A., Haddad, L., Laborde, D., Stegmuller, A., Thomas, M., and Heidkamp, R. (2021). The COVID-19 crisis will exacerbate maternal and child undernutrition and child mortality in low- and middle-income countries. Nature Food, 2, 476-484. https://doi.org/10.1038/s43016-021-00319-4",
    "Rentschler, J., Salhab, M., and Jafino, B. A. (2022). Flood exposure and poverty in 188 countries. Nature Communications, 13, 3527. https://doi.org/10.1038/s41467-022-30727-4",
    "Sen, A. (1999). Development as Freedom. Oxford: Oxford University Press.",
    "Skoufias, E., Katayama, R., Essama-Nssah, B., and Cusolito, A. (2013). Disquiet on the Weather Front: The Welfare Impacts of Climatic Variability in the Rural Philippines. Washington, DC: World Bank.",
    "Somanathan, E., Somanathan, R., Sudarshan, A., and Tewari, M. (2021). The impact of temperature on productivity and labor supply: Evidence from Indian manufacturing. Journal of Political Economy, 129(6), 1797-1827. https://doi.org/10.1086/713733",
    "Tellman, B., Sullivan, J. A., Kuhn, C., Kettner, A. J., Doyle, C. S., Brakenridge, G. R., Erickson, T. A., and Slayback, D. A. (2021). Satellite imaging reveals increased proportion of population exposed to floods. Nature, 596, 80-86. https://doi.org/10.1038/s41586-021-03695-w",
    "UNICEF. (2021). Direct and Indirect Effects of COVID-19 Pandemic and Response in South Asia. Kathmandu: UNICEF Regional Office for South Asia.",
    "United Nations Development Programme. (1990). Human Development Report 1990. New York: Oxford University Press.",
    "United Nations Development Programme. (2022a). Addressing the Cost-of-Living Crisis in Developing Countries: Poverty and Vulnerability Projections and Policy Responses. New York: UNDP.",
    "United Nations Development Programme. (2022b). Afghanistan Socio-Economic Outlook 2021-2022. Kabul: UNDP.",
    "Vicedo-Cabrera, A. M., Scovronick, N., Sera, F., Roye, D., Schneider, R., Tobias, A., Astrom, C., et al. (2021). The burden of heat-related mortality attributable to recent human-induced climate change. Nature Climate Change, 11, 492-500. https://doi.org/10.1038/s41558-021-01058-x",
    "World Bank. (2017). Mongolia Poverty Update 2016. Washington, DC: World Bank.",
    "World Bank. (2021a). Uneven Recovery: East Asia and Pacific Economic Update, April 2021. Washington, DC: World Bank.",
    "World Bank. (2021b). Long COVID: East Asia and Pacific Economic Update, October 2021. Washington, DC: World Bank.",
    "World Bank. (2022a). Reforms for Recovery: East Asia and Pacific Economic Update, October 2022. Washington, DC: World Bank.",
    "World Bank. (2022b). Preliminary Assessment of Hunga Tonga-Hunga Ha'apai Volcanic Eruption and Tsunami in Tonga Using the GRADE Methodology. Washington, DC: World Bank.",
    "World Bank. (2023a). Collapse and Recovery: How COVID-19 Eroded Human Capital and What to Do About It. Washington, DC: World Bank.",
    "World Bank. (2023b). Sri Lanka Development Update: Mobilizing Tax Revenue for a Better Future. Washington, DC: World Bank.",
    "World Bank. (2024a). Lao People's Democratic Republic Economic Monitor and Household Welfare Monitoring. Washington, DC: World Bank.",
    "World Bank. (2024b). Myanmar Economic Monitor: Livelihoods under Threat. Washington, DC: World Bank.",
    "World Bank. (2025). East Asia and Pacific Economic Update, April 2025: The Hard Road to Growth. Washington, DC: World Bank.",
    "World Health Organization. (2022). Global Excess Deaths Associated with the COVID-19 Pandemic, 2020-2021. Geneva: WHO.",
    "Yarrow, N., Masood, E., and Afkar, R. (2020). Estimates of COVID-19 Impacts on Learning and Earning in Indonesia: How to Turn the Tide. Washington, DC: World Bank."
    'Banerjee, R., and Maharaj, R. (2019). Heat, infant mortality, and adaptation: Evidence from India. Journal of Development Economics. https://doi.org/10.1016/j.jdeveco.2019.102378',
    'Giannelli, G. C., and Canessa, E. (2021). After the Flood: Migration and Remittances as Coping Strategies of Rural Bangladeshi Households. Economic Development and Cultural Change. https://doi.org/10.1086/713939',
    'Tiwari, S., Jacoby, H. G., and Skoufias, E. (2016). Monsoon Babies: Rainfall Shocks and Child Nutrition in Nepal. Economic Development and Cultural Change. https://doi.org/10.1086/689308',
]


ANNOTATED_IDS = [
    "C01", "C02", "C03", "C04", "C06", "C08", "C09", "C11", "C12", "C14",
    "E01", "E05", "E10", "N01", "N02", "N07", "N08", "N10", "N12", "N14"
]
