#!/usr/bin/env node
// scripts/build-slides.mjs
// Builds the slide deck for a single program: regenerates the charts from
// the latest committed CSVs, then runs `quarto render` to produce the
// .pptx into reporting-site/public/programs/{slug}/.
//
// Implements the slide-deck rule in research/factory.md: source of record
// is the markdown at articles/_slides/{slug}.md; the .pptx is a built
// artifact deterministically regenerated from the markdown source. The
// charts on the slides are first regenerated by the per-program build
// script, then embedded by Quarto — guaranteeing the slide chart cannot
// drift from the working paper's chart.

import { execSync, execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");

const slug = process.argv[2] || "public-service-data-quality";
const slideSrc = path.join(REPO_ROOT, "articles", "_slides", `${slug}.md`);
const programDir = path.join(REPO_ROOT, slug);
const destDir = path.join(REPO_ROOT, "reporting-site", "public", "programs", slug);
const destPptx = path.join(destDir, `${slug}-deck.pptx`);

// Find the program's chart-build script. Convention: `scripts/build-*.py`
// whose filename contains "chart" or "choropleth" (the two patterns used in
// the lab so far). This lets a new program ship its own build-*.py without
// modifying this script.
function findChartScript() {
  const fixed = path.join(programDir, "scripts", "build-choropleth.py");
  if (fs.existsSync(fixed)) return fixed;
  const scriptsDir = path.join(programDir, "scripts");
  if (!fs.existsSync(scriptsDir)) return null;
  const candidates = fs.readdirSync(scriptsDir)
    .filter((f) => f.startsWith("build-") && f.endsWith(".py"))
    .filter((f) => f.toLowerCase().includes("chart") || f.toLowerCase().includes("choropleth"));
  return candidates.length > 0 ? path.join(scriptsDir, candidates[0]) : null;
}
const chartScript = findChartScript();

if (!fs.existsSync(slideSrc)) {
  console.error(`No slide source at ${slideSrc}`);
  process.exit(1);
}

// Locate Quarto. Prefer PATH, fall back to the standard Windows install
// path because the current shell may not have refreshed PATH after install.
function findQuarto() {
  try {
    execSync("quarto --version", { stdio: "ignore" });
    return "quarto";
  } catch {}
  const candidates = [
    "C:\\Program Files\\Quarto\\bin\\quarto.exe",
    "/usr/local/bin/quarto",
    "/opt/quarto/bin/quarto",
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  console.error("Quarto not found on PATH or standard install paths.");
  console.error("Install via `winget install Posit.Quarto` or download from quarto.org.");
  process.exit(1);
}

const quarto = findQuarto();
console.log(`Using quarto at: ${quarto === "quarto" ? "PATH" : quarto}`);

// Step 1 — regenerate charts from latest CSVs (so the slide chart cannot
// drift from the working paper's chart). execFileSync passes argv as a
// list — slug-bearing paths are not interpolated into a shell string, so
// odd characters in slug cannot inject.
if (chartScript && fs.existsSync(chartScript)) {
  console.log(`\n[1/2] Regenerating charts via ${path.relative(REPO_ROOT, chartScript)}`);
  execFileSync("python", [chartScript], { stdio: "inherit", cwd: REPO_ROOT });
} else {
  console.log(`\n[1/2] No build-*chart*.py / build-choropleth.py for ${slug}; skipping chart refresh.`);
}

// Step 2 — Quarto render in place, then move to final destination.
// Quarto resolves --output-dir relative to the input file's directory and
// strips path components in some versions, so the most reliable approach
// is to render next to the source and then move the artifact ourselves.
fs.mkdirSync(destDir, { recursive: true });
console.log(`\n[2/2] Quarto render → ${path.relative(REPO_ROOT, destPptx)}`);

const slideDir = path.dirname(slideSrc);
const slideBase = path.basename(slideSrc, ".md");
const intermediatePptx = path.join(slideDir, `${slideBase}.pptx`);

execFileSync(quarto, ["render", slideSrc, "--to", "pptx"], { stdio: "inherit", cwd: REPO_ROOT });

if (!fs.existsSync(intermediatePptx)) {
  console.error(`\nQuarto did not produce ${intermediatePptx}. Check output above.`);
  process.exit(1);
}

fs.copyFileSync(intermediatePptx, destPptx);
fs.unlinkSync(intermediatePptx);

const size = fs.statSync(destPptx).size;
const sizeKb = (size / 1024).toFixed(1);
console.log(`\nDone. ${path.relative(REPO_ROOT, destPptx)} (${sizeKb} KB)`);
