#!/usr/bin/env node
// scripts/coverage-matrix.mjs
// Generates research/coverage-matrix.md from the JSON outputs each
// program writes into reporting-site/public/data/. Each JSON is expected
// to be an array of rows with at least `iso3` (string).

import fs from "node:fs";
import path from "node:path";

const DATA_DIR = "reporting-site/public/data";
const OUT = "research/coverage-matrix.md";

const PROGRAM_LABELS = {
  "mpi-nighttime-lights": "mpi-ntl",
  "public-service-data-quality": "psdq",
  "access-services": "acc",
  "air-monitoring": "air",
  "remittance-resilience": "rem",
  "grid-reliability-heat": "grid",
  "disaster-recovery-lag": "dis",
  "migration-displacement-signals": "mig",
  "port-hinterland-friction": "port",
  "water-stress-crop-diversification": "water",
  "climate-health-workdays": "clim",
  "social-protection-shock-coverage": "sp",
  "school-heat-disruption": "sch",
  "food-price-climate-transmission": "food",
};

function listProgramFiles() {
  if (!fs.existsSync(DATA_DIR)) return [];
  return fs.readdirSync(DATA_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => path.join(DATA_DIR, f));
}

function loadProgram(file) {
  try {
    const data = JSON.parse(fs.readFileSync(file, "utf8"));
    const slug = path.basename(file, ".json");
    return { slug, rows: Array.isArray(data) ? data : (data.rows ?? data.items ?? []) };
  } catch (e) {
    return { slug: path.basename(file, ".json"), rows: [] };
  }
}

function isos(rows) {
  const set = new Set();
  for (const r of rows) {
    if (typeof r?.iso3 === "string") set.add(r.iso3.toUpperCase());
    else if (typeof r?.ISO3 === "string") set.add(r.ISO3.toUpperCase());
    else if (typeof r?.country_iso3 === "string") set.add(r.country_iso3.toUpperCase());
  }
  return set;
}

function main() {
  const programs = listProgramFiles().map(loadProgram);
  const slugs = Array.from(new Set(programs.map((p) => p.slug)));
  const programIsos = new Map(programs.map((p) => [p.slug, isos(p.rows)]));

  // Union of all observed ISO3s across programs.
  const allIsos = new Set();
  for (const set of programIsos.values()) for (const iso of set) allIsos.add(iso);
  const isoList = [...allIsos].sort();

  const labels = slugs.map((s) => PROGRAM_LABELS[s] ?? s);
  const header = ["ISO3", ...labels];
  const rows = isoList.map((iso) => {
    const cells = slugs.map((slug) => {
      const set = programIsos.get(slug) ?? new Set();
      return set.has(iso) ? "✓" : "·";
    });
    return [iso, ...cells];
  });

  // Coverage rates per program
  const perProgram = slugs.map((slug, i) => {
    const set = programIsos.get(slug) ?? new Set();
    const covered = set.size;
    const inScope = covered;
    return { label: labels[i], slug, inScope, covered, rate: inScope ? Math.round(100 * covered / inScope) : 0 };
  });

  // Coverage rates per DMC
  const perDmc = isoList.map((iso) => {
    const inScope = slugs.length;
    const covered = slugs.filter((slug) => (programIsos.get(slug) ?? new Set()).has(iso)).length;
    return { iso, inScope, covered, rate: inScope ? Math.round(100 * covered / inScope) : 0 };
  });

  const md = renderMd({ header, rows, perProgram, perDmc, programs: slugs.length, isos: isoList.length });
  fs.writeFileSync(OUT, md);
  console.log(`wrote ${OUT} — ${slugs.length} programs × ${isoList.length} DMCs.`);
}

function renderMd({ header, rows, perProgram, perDmc, programs, isos: nIsos }) {
  const headSep = header.map((_, i) => i === 0 ? "---" : "---");
  const matrix = [
    `| ${header.join(" | ")} |`,
    `| ${headSep.join(" | ")} |`,
    ...rows.map((r) => `| ${r.join(" | ")} |`),
  ].join("\n");

  const perProg = [
    `| Program | DMCs covered | Coverage rate |`,
    `| --- | --- | --- |`,
    ...perProgram.map((p) => `| ${p.label} | ${p.covered} | ${p.rate}% |`),
  ].join("\n");

  const perDm = [
    `| ISO3 | Programs covered | Coverage rate |`,
    `| --- | --- | --- |`,
    ...perDmc.map((d) => `| ${d.iso} | ${d.covered} / ${d.inScope} | ${d.rate}% |`),
  ].join("\n");

  return `# Coverage matrix

Auto-generated by \`scripts/coverage-matrix.mjs\` from \`${DATA_DIR}/*.json\`.
Do not edit by hand. Re-run the script after a pipeline run.

Last refresh: ${new Date().toISOString().slice(0, 10)} (${programs} programs × ${nIsos} DMCs)

---

## Matrix

${matrix}

Cell legend:
- ✓ — value present in the program's JSON output
- · — DMC not present (out of scope or pipeline not yet covering this DMC)

---

## Per-program coverage

${perProg}

---

## Per-DMC coverage

${perDm}
`;
}

main();
