// Local article index loader. The list is generated by
// scripts/sync-articles.mjs at predev/prebuild and lives at
// /articles/_index.json in the public folder.

export interface ArticleMeta {
  slug: string;
  title: string;
  subtitle: string;
  kind: "blog" | "brief" | "working-paper" | "journal" | "dataset-doc" | string;
  // Publication-ladder tier (assigned by scripts/sync-articles.mjs from
  // the source directory: top-level articles/*.md → "working-paper",
  // articles/_brief/ → "brief", _blog → "blog", _social → "social",
  // _slides → "slides").
  tier: "working-paper" | "brief" | "blog" | "social" | "slides" | string;
  status: "draft" | "review" | "published" | "retracted" | string;
  program: string;
  maturity: string;
  topics: string[];
  geographies: string[];
  abstract: string;
  authors: string[];
  published_at: string;
  updated_at: string;
  doi: string;
  file: string;
  attestation_chain?: "ai-first" | "human-final" | "mixed" | string;
  constitution_ref?: string;
  review_external_chain?: string;
  review_internal_chain?: string;
}

let _cache: Promise<ArticleMeta[]> | null = null;

export function loadArticleIndex(): Promise<ArticleMeta[]> {
  if (!_cache) {
    _cache = fetch("/articles/_index.json")
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => []);
  }
  return _cache;
}

export async function loadArticleBody(slug: string): Promise<string | null> {
  const index = await loadArticleIndex();
  const meta = index.find((a) => a.slug === slug);
  if (!meta) return null;
  const r = await fetch(`/articles/${meta.file}`);
  if (!r.ok) return null;
  return r.text();
}

export function stripFrontmatter(md: string): string {
  if (!md.startsWith("---")) return md;
  const end = md.indexOf("\n---", 3);
  if (end < 0) return md;
  return md.slice(end + 4).replace(/^\r?\n/, "");
}
