import { createWriteStream } from "fs";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { Readable } from "stream";
import { finished } from "stream/promises";

const PILOTS = [
  {
    iso2: "PH",
    iso3: "PHL",
    name: "Philippines",
    bbox: { minLon: 116.9, minLat: 4.5, maxLon: 127.0, maxLat: 21.3 },
  },
  {
    iso2: "BD",
    iso3: "BGD",
    name: "Bangladesh",
    bbox: { minLon: 88.0, minLat: 20.5, maxLon: 92.8, maxLat: 26.7 },
  },
];

const YEAR = Number(process.env.OOKLA_YEAR ?? 2026);
const QUARTER = Number(process.env.OOKLA_QUARTER ?? 1);
const DOWNLOAD = process.env.OOKLA_DOWNLOAD === "1";
const OUTPUTS = [
  "src/data/generated/digital-performance-ookla-pilots.json",
  "public/data/digital-performance-ookla-pilots.json",
];

function quarterStart(year: number, quarter: number): string {
  const month = String((quarter - 1) * 3 + 1).padStart(2, "0");
  return `${year}-${month}-01`;
}

function ooklaUrl(type: "mobile" | "fixed"): string {
  const date = quarterStart(YEAR, QUARTER);
  return `https://ookla-open-data.s3.amazonaws.com/parquet/performance/type=${type}/year=${YEAR}/quarter=${QUARTER}/${date}_performance_${type}_tiles.parquet`;
}

function buildDuckDbSql(type: "mobile" | "fixed"): string {
  const url = ooklaUrl(type);
  const pilotSelects = PILOTS.map(
    (country) => `select
  '${country.iso3}' as iso3,
  '${country.name}' as economy,
  '${type}' as network_type,
  count(*) as measured_tiles,
  sum(tests) as tests,
  sum(devices) as devices,
  round(avg(avg_d_kbps) / 1000, 2) as mean_download_mbps,
  round(avg(avg_u_kbps) / 1000, 2) as mean_upload_mbps,
  round(avg(avg_lat_ms), 2) as mean_latency_ms
from ookla_tiles
where tile_x between ${country.bbox.minLon} and ${country.bbox.maxLon}
  and tile_y between ${country.bbox.minLat} and ${country.bbox.maxLat}`
  ).join("\nunion all\n");

  return `-- Generated by scripts/research/fetch-ookla-pilots.ts
-- Requires DuckDB with httpfs support.
install httpfs;
load httpfs;

create or replace temp view ookla_tiles as
select * from read_parquet('${url}');

copy (
${pilotSelects}
) to 'research/digital-performance/generated/ookla-${type}-${YEAR}-q${QUARTER}-pilot-summary.csv' with (header, delimiter ',');
`;
}

async function writeOutputs(data: unknown): Promise<void> {
  for (const relativePath of OUTPUTS) {
    const outputPath = path.join(process.cwd(), relativePath);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, `${JSON.stringify(data, null, 2)}\n`);
  }
}

async function downloadFile(url: string, outputPath: string): Promise<number> {
  const response = await fetch(url, {
    headers: { "User-Agent": "DevelopmentBlindspotsLab/0.1 research pipeline" },
  });

  if (!response.ok || !response.body) {
    throw new Error(`Failed to download ${url}: HTTP ${response.status}`);
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  const stream = createWriteStream(outputPath);
  await finished(Readable.fromWeb(response.body).pipe(stream));
  return Number(response.headers.get("content-length") ?? 0);
}

async function main(): Promise<void> {
  const manifests = (["mobile", "fixed"] as const).map((type) => ({
    type,
    year: YEAR,
    quarter: QUARTER,
    url: ooklaUrl(type),
    localPath: `research/digital-performance/raw/ookla/${YEAR}-q${QUARTER}-${type}.parquet`,
    duckdbSqlPath: `research/digital-performance/generated/ookla-${type}-${YEAR}-q${QUARTER}.sql`,
  }));

  for (const manifest of manifests) {
    const sqlPath = path.join(process.cwd(), manifest.duckdbSqlPath);
    await mkdir(path.dirname(sqlPath), { recursive: true });
    await writeFile(sqlPath, buildDuckDbSql(manifest.type));

    if (DOWNLOAD) {
      console.log(`Downloading ${manifest.type} Ookla parquet...`);
      const localPath = path.join(process.cwd(), manifest.localPath);
      await downloadFile(manifest.url, localPath);
    }
  }

  const output = {
    metadata: {
      title: "Ookla Pilot Download and Aggregation Manifest",
      generatedAt: new Date().toISOString(),
      script: "scripts/research/fetch-ookla-pilots.ts",
      status: DOWNLOAD ? "download_attempted" : "manifest_and_sql_ready",
      source: "https://github.com/teamookla/ookla-open-data",
      caveat:
        "Ookla files are global quarterly parquet files. The script writes DuckDB SQL for bounding-box pilot aggregation and only downloads the large files when OOKLA_DOWNLOAD=1.",
      year: YEAR,
      quarter: QUARTER,
    },
    pilots: PILOTS,
    manifests,
  };

  await writeOutputs(output);
  console.log("Wrote Ookla manifest outputs and DuckDB SQL files.");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
